blueprint:
  name: Motion Light – Advanced (Day/Night, Fade, Manual Override)
  description: >
    Motion-activated light with day/night brightness, separate timeouts,
    manual override detection, optional "only if light is off", and fade-in/out transitions.
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    target_light:
      name: Light
      selector:
        entity:
          domain: light

    day_brightness:
      name: Day Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    night_brightness:
      name: Night Brightness (%)
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    day_timeout:
      name: Day No-Motion Timeout
      default: "00:03:00"
      selector:
        duration:

    night_timeout:
      name: Night No-Motion Timeout
      default: "00:05:00"
      selector:
        duration:

    only_if_off:
      name: Only turn on if light is off
      description: If enabled, motion will not re-trigger if the light is already on.
      default: true
      selector:
        boolean:

    day_fade:
      name: Day Fade Duration (seconds)
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds

    night_fade:
      name: Night Fade Duration (seconds)
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds

    off_fade:
      name: Fade Duration When Turning Off (seconds)
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds


trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

action:
  # Optional: only act if light is off
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ not is_state('!input target_light', 'on')
                 or not !input only_if_off }}
        sequence: []
    default:
      - stop: "Light already on and only_if_off enabled"

  # Turn on light with fade (day/night)
  - choose:
      # Daytime
      - conditions:
          - condition: sun
            after: sunrise
            before: sunset
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_pct: !input day_brightness
              transition: !input day_fade

      # Nighttime
      - conditions:
          - condition: sun
            after: sunset
            before: sunrise
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_pct: !input night_brightness
              transition: !input night_fade

  # Wait for either:
  # 1) Manual light off (override)
  # 2) Motion stopped long enough (day/night timeout)
  - wait_for_trigger:
      - platform: state
        entity_id: !input target_light
        to: "off"

      - platform: state
        entity_id: !input motion_sensor
        to: "off"
        for: >
          {% if is_state('sun.sun', 'above_horizon') %}
            {{ !input day_timeout }}
          {% else %}
            {{ !input night_timeout }}
          {% endif %}

  # If light was manually turned off → stop
  - condition: state
    entity_id: !input target_light
    state: "on"

  # Auto turn-off with fade
  - service: light.turn_off
    target:
      entity_id: !input target_light
    data:
      transition: !input off_fade

mode: restart
